#!/bin/bash

set -e

TIMESTAMP=`date +%F_%Hh%Mm%Ss`
: ${LOGDIR:="$HOME/log/$TIMESTAMP"}

GPS_PORT=/dev/ttyS0
AHRS_PORT=/dev/ttyS1
AEROPROBE_PORT=/dev/ttyS2

mkdir -p $LOGDIR

vcmdas1-read --logtxt=$LOGDIR/adc.log &
ahrs400-read --logtxt=$LOGDIR/ahrs.log $AHRS_PORT &
python3 -m pyfdas.gps --logtxtdir=$LOGDIR $GPS_PORT &
mavlog $AEROPROBE_PORT $LOGDIR/aeroprobe.mavlog &
